CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE administrators (
    admin_id integer GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(20),
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_administrators" PRIMARY KEY (admin_id)
);

CREATE TABLE cities (
    city_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    CONSTRAINT "PK_cities" PRIMARY KEY (city_id)
);

CREATE TABLE clients (
    client_id integer GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(20),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_clients" PRIMARY KEY (client_id)
);

CREATE TABLE equipment_types (
    type_id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    description text,
    CONSTRAINT "PK_equipment_types" PRIMARY KEY (type_id)
);

CREATE TABLE studios (
    studio_id integer GENERATED BY DEFAULT AS IDENTITY,
    admin_id integer NOT NULL,
    city_id integer NOT NULL,
    name character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    description text,
    photo_url character varying(500),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_studios" PRIMARY KEY (studio_id),
    CONSTRAINT "FK_studios_administrators_admin_id" FOREIGN KEY (admin_id) REFERENCES administrators (admin_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_studios_cities_city_id" FOREIGN KEY (city_id) REFERENCES cities (city_id) ON DELETE RESTRICT
);

CREATE TABLE rooms (
    room_id integer GENERATED BY DEFAULT AS IDENTITY,
    studio_id integer NOT NULL,
    name character varying(255) NOT NULL,
    area_sqm numeric(6,2) NOT NULL,
    price_per_hour numeric(10,2) NOT NULL,
    is_available boolean NOT NULL DEFAULT TRUE,
    description text,
    photo_url character varying(500),
    CONSTRAINT "PK_rooms" PRIMARY KEY (room_id),
    CONSTRAINT "FK_rooms_studios_studio_id" FOREIGN KEY (studio_id) REFERENCES studios (studio_id) ON DELETE CASCADE
);

CREATE TABLE bookings (
    booking_id integer GENERATED BY DEFAULT AS IDENTITY,
    client_id integer NOT NULL,
    room_id integer NOT NULL,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    total_price numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    note text,
    CONSTRAINT "PK_bookings" PRIMARY KEY (booking_id),
    CONSTRAINT "FK_bookings_clients_client_id" FOREIGN KEY (client_id) REFERENCES clients (client_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_bookings_rooms_room_id" FOREIGN KEY (room_id) REFERENCES rooms (room_id) ON DELETE RESTRICT
);

CREATE TABLE equipment (
    equipment_id integer GENERATED BY DEFAULT AS IDENTITY,
    room_id integer NOT NULL,
    type_id integer NOT NULL,
    name character varying(255) NOT NULL,
    condition character varying(50),
    price_per_hour numeric(10,2) NOT NULL,
    CONSTRAINT "PK_equipment" PRIMARY KEY (equipment_id),
    CONSTRAINT "FK_equipment_equipment_types_type_id" FOREIGN KEY (type_id) REFERENCES equipment_types (type_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_equipment_rooms_room_id" FOREIGN KEY (room_id) REFERENCES rooms (room_id) ON DELETE CASCADE
);

CREATE TABLE booking_equipment (
    booking_equipment_id integer GENERATED BY DEFAULT AS IDENTITY,
    booking_id integer NOT NULL,
    equipment_id integer NOT NULL,
    price_snapshot numeric(10,2) NOT NULL,
    CONSTRAINT "PK_booking_equipment" PRIMARY KEY (booking_equipment_id),
    CONSTRAINT "FK_booking_equipment_bookings_booking_id" FOREIGN KEY (booking_id) REFERENCES bookings (booking_id) ON DELETE CASCADE,
    CONSTRAINT "FK_booking_equipment_equipment_equipment_id" FOREIGN KEY (equipment_id) REFERENCES equipment (equipment_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_administrators_email" ON administrators (email);

CREATE INDEX "IX_booking_equipment_booking_id" ON booking_equipment (booking_id);

CREATE INDEX "IX_booking_equipment_equipment_id" ON booking_equipment (equipment_id);

CREATE INDEX "IX_bookings_client_id" ON bookings (client_id);

CREATE INDEX "IX_bookings_room_id" ON bookings (room_id);

CREATE UNIQUE INDEX "IX_cities_name" ON cities (name);

CREATE UNIQUE INDEX "IX_clients_email" ON clients (email);

CREATE INDEX "IX_equipment_room_id" ON equipment (room_id);

CREATE INDEX "IX_equipment_type_id" ON equipment (type_id);

CREATE UNIQUE INDEX "IX_equipment_types_name" ON equipment_types (name);

CREATE INDEX "IX_rooms_studio_id" ON rooms (studio_id);

CREATE INDEX "IX_studios_admin_id" ON studios (admin_id);

CREATE INDEX "IX_studios_city_id" ON studios (city_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260426135301_InitialCreate', '8.0.11');

COMMIT;

START TRANSACTION;

-- Indexes justified by typical user queries
-- idx_studio_city_id: used by /api/studios?cityId= filter
CREATE INDEX IF NOT EXISTS idx_studio_city_id ON studios(city_id);

-- idx_room_studio_id: used by /api/studios/:id to list rooms
CREATE INDEX IF NOT EXISTS idx_room_studio_id ON rooms(studio_id);

-- idx_booking_room_date: used for overlap check and /bookings list filtered by room+date
CREATE INDEX IF NOT EXISTS idx_booking_room_date ON bookings(room_id, date);

-- idx_booking_client_id: used by /api/bookings/mine for client's own bookings
CREATE INDEX IF NOT EXISTS idx_booking_client_id ON bookings(client_id);

-- idx_equipment_room_id: used by /api/rooms/:id to list equipment
CREATE INDEX IF NOT EXISTS idx_equipment_room_id ON equipment(room_id);


-- Trigger 1: Prevent overlapping bookings for the same room on the same date.
-- Guards against double-booking regardless of application-layer checks.
CREATE OR REPLACE FUNCTION fn_booking_no_overlap()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM bookings
        WHERE room_id = NEW.room_id
          AND date = NEW.date
          AND booking_id <> COALESCE(NEW.booking_id, -1)
          AND status IN ('Pending', 'Confirmed')
          AND start_time < NEW.end_time
          AND end_time > NEW.start_time
    ) THEN
        RAISE EXCEPTION 'Room % is already booked on % from % to %',
            NEW.room_id, NEW.date, NEW.start_time, NEW.end_time;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_booking_no_overlap ON bookings;
CREATE TRIGGER trg_booking_no_overlap
    BEFORE INSERT OR UPDATE ON bookings
    FOR EACH ROW EXECUTE FUNCTION fn_booking_no_overlap();


-- Trigger 2: Auto-calculate Booking.total_price on insert/update.
-- Formula: duration_hours × room.price_per_hour + SUM(be.price_snapshot) × duration_hours
CREATE OR REPLACE FUNCTION fn_booking_calc_total_price()
RETURNS TRIGGER AS $$
DECLARE
    v_room_price   DECIMAL(10,2);
    v_equip_price  DECIMAL(10,2);
    v_duration_hrs DECIMAL(10,4);
BEGIN
    SELECT price_per_hour INTO v_room_price FROM rooms WHERE room_id = NEW.room_id;

    v_duration_hrs := EXTRACT(EPOCH FROM (NEW.end_time - NEW.start_time)) / 3600.0;

    SELECT COALESCE(SUM(price_snapshot), 0) INTO v_equip_price
    FROM booking_equipment WHERE booking_id = NEW.booking_id;

    NEW.total_price := ROUND((v_room_price + v_equip_price) * v_duration_hrs, 2);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_booking_calc_total_price ON bookings;
CREATE TRIGGER trg_booking_calc_total_price
    BEFORE INSERT OR UPDATE ON bookings
    FOR EACH ROW EXECUTE FUNCTION fn_booking_calc_total_price();


-- Trigger 3: Auto-set BookingEquipment.price_snapshot from Equipment.price_per_hour on insert.
-- Ensures the snapshot reflects the price at time of booking, not future edits.
CREATE OR REPLACE FUNCTION fn_be_price_snapshot()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.price_snapshot IS NULL OR NEW.price_snapshot = 0 THEN
        SELECT price_per_hour INTO NEW.price_snapshot
        FROM equipment WHERE equipment_id = NEW.equipment_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_be_price_snapshot ON booking_equipment;
CREATE TRIGGER trg_be_price_snapshot
    BEFORE INSERT ON booking_equipment
    FOR EACH ROW EXECUTE FUNCTION fn_be_price_snapshot();


-- Trigger 4: Auto-update updated_at on Studios, Administrators, and Clients.
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_studio_updated_at ON studios;
CREATE TRIGGER trg_studio_updated_at
    BEFORE UPDATE ON studios
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_admin_updated_at ON administrators;
CREATE TRIGGER trg_admin_updated_at
    BEFORE UPDATE ON administrators
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_client_updated_at ON clients;
CREATE TRIGGER trg_client_updated_at
    BEFORE UPDATE ON clients
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();


-- Stored Procedure 5: Studio occupancy report for last N months.
-- Returns per-studio, per-month booking count and occupied hours.
CREATE OR REPLACE FUNCTION sp_studio_occupancy_report(p_months INT DEFAULT 7)
RETURNS TABLE (
    studio_id    INT,
    studio_name  TEXT,
    report_year  INT,
    report_month INT,
    total_bookings INT,
    occupied_hours DECIMAL(10,2)
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        s.studio_id,
        s.name::TEXT,
        EXTRACT(YEAR  FROM b.date::DATE)::INT  AS report_year,
        EXTRACT(MONTH FROM b.date::DATE)::INT  AS report_month,
        COUNT(b.booking_id)::INT               AS total_bookings,
        ROUND(SUM(
            EXTRACT(EPOCH FROM (b.end_time - b.start_time)) / 3600.0
        )::NUMERIC, 2)                         AS occupied_hours
    FROM bookings b
    JOIN rooms r ON r.room_id = b.room_id
    JOIN studios s ON s.studio_id = r.studio_id
    WHERE b.date >= (CURRENT_DATE - (p_months || ' months')::INTERVAL)::DATE
      AND b.status IN ('Confirmed', 'Completed')
    GROUP BY s.studio_id, s.name, report_year, report_month
    ORDER BY s.studio_id, report_year, report_month;
END;
$$ LANGUAGE plpgsql;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260426135309_ApplySqlScripts', '8.0.11');

COMMIT;

